- id: enable_zigbee_join
  alias: Enable Zigbee joining
  trigger:
    platform: state
    entity_id: input_boolean.zigbee_permit_join
    to: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'true'
  - service: timer.start
    data:
      entity_id: timer.zigbee_permit_join
- id: disable_zigbee_join
  alias: Disable Zigbee joining
  trigger:
  - entity_id: input_boolean.zigbee_permit_join
    platform: state
    to: 'off'
  action:
  - data:
      payload: 'false'
      topic: zigbee2mqtt/bridge/config/permit_join
    service: mqtt.publish
  - data:
      entity_id: timer.zigbee_permit_join
    service: timer.cancel
- id: disable_zigbee_join_timer
  alias: Disable Zigbee joining by timer
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.zigbee_permit_join
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'false'
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.zigbee_permit_join
- id: update_networkmap
  alias: Zigbee Map Update
  trigger:
    platform: time_pattern
    minutes: /10
    seconds: 0
  action:
    service: zigbee2mqtt_networkmap.update
- id: '1587960507517'
  alias: Turn on living room lamp
  description: ''
  trigger:
  - event: sunset
    offset: -00:20:00
    platform: sun
  condition: []
  action:
  - data: {}
    entity_id: switch.living_lamp
    service: switch.turn_on
- id: '1588724019082'
  alias: send notification when Amy D leaves Dar's House
  description: ''
  trigger:
  - entity_id: person.amy_d
    event: leave
    platform: zone
    zone: zone.dar_s_house
  condition: []
  action:
  - data:
      message: Amy Left Dar's House
    service: notify.telegram_brenton
- id: '1591154308336'
  alias: 20min garage open alert
  description: ''
  trigger:
  - device_id: 8e771c0b255d4b36bfcff005b44518a6
    domain: binary_sensor
    entity_id: binary_sensor.garage_door_sensor_contact
    for:
      hours: 0
      minutes: 20
      seconds: 0
    platform: device
    type: opened
  condition: []
  action:
  - data:
      message: Garage Door may have been open for 20+ minutes
    service: notify.telegram_brenton
  - data:
      message: Garage Door may have been open for 20+ minutes
    service: notify.telegram_amy
- id: '1600659867634'
  alias: switch off living_lamp when its midnight and no one is home
  description: ''
  trigger:
  - platform: time
    at: '23:55'
  condition:
  - condition: device
    device_id: 5c587f21890e440fab2cb9e2d9634716
    domain: device_tracker
    entity_id: device_tracker.sm_g977b
    type: is_not_home
  - condition: device
    device_id: b3cd29707da14763a6a18f523b4996e7
    domain: device_tracker
    entity_id: device_tracker.amys_iphone
    type: is_not_home
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.living_lamp
  mode: single
- id: '1600726741112'
  alias: Garage open nobody home
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 8e771c0b255d4b36bfcff005b44518a6
    entity_id: binary_sensor.garage_door_sensor_contact
    domain: binary_sensor
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition:
  - condition: device
    device_id: b3cd29707da14763a6a18f523b4996e7
    domain: device_tracker
    entity_id: device_tracker.amys_iphone
    type: is_not_home
  - condition: device
    device_id: 5c587f21890e440fab2cb9e2d9634716
    domain: device_tracker
    entity_id: device_tracker.sm_g977b
    type: is_not_home
  action:
  - service: notify.telegram_brenton
    data:
      message: Garage Door Open & Nobody is Home!
  mode: single
