###############################################################
# Home Assistant Main Configuration File
# This file sets up integrations, automations, and customizations
###############################################################

# Default setup (frontend, API, etc.)
default_config:

# Frontend configuration
frontend:
  themes: !include themes.yaml  # Loads custom themes
  extra_module_url:
    - \config\www\community\lovelace-card-mod/card-mod.js  # Card mod for Lovelace UI
#media_extractor:  # Uncomment to enable media extractor integration

# Uncomment below if using SSL/TLS or running in Docker
#http:
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

# Zigbee2MQTT integration controls
input_boolean:
  zigbee_permit_join:
    name: Allow devices to join  # Toggle for Zigbee device joining
    initial: off
    icon: mdi:cellphone-wireless

# Timer for Zigbee2MQTT device joining
timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 600 # Set timer to 600 seconds

# Text-to-speech integration
tts:
  - platform: google_translate  # Uses Google Translate for TTS

# Notify configuration for Telegram
notify:
  - name: telegram_brenton
    platform: telegram
    chat_id: !secret brenton_chatid
  - name: telegram_amy
    platform: telegram
    chat_id: !secret amy_chatid

# Enables webhook support
webhook:

# Home Assistant customizations
homeassistant:
  customize:
    # Set rain rate sensors to total_increasing state class
    sensor.gw1100c_v2_1_4_hourly_rain_rate:
      state_class: total_increasing
    sensor.gw1100c_v2_1_4_daily_rain_rate:
      state_class: total_increasing
    sensor.gw1100c_v2_1_4_weekly_rain_rate:
      state_class: total_increasing
    sensor.gw1100c_v2_1_4_monthly_rain_rate:
      state_class: total_increasing
    sensor.gw1100c_v2_1_4_yearly_rain_rate:
      state_class: total_increasing
    sensor.gw1100c_v2_1_4_event_rain_rate:
      state_class: total_increasing

# Sonos Cloud integration
sonos_cloud:
  client_id: !secret sonos_id
  client_secret: !secret sonos_secret

# Include additional configuration files
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
template: !include template.yaml