
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
frontend:
  themes: !include themes.yaml

media_extractor:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Zigbee2mqtt MQTT Broker Config
mqtt:
  broker: homeassistant # This will have to be your mqtt broker, Mosquitto addon is recommended.
  discovery: true
  username: brenton
  password: !secret mqtt_password

# Zigbee2MQTT Card
input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless
    
# Timer for Zigbee2MQTT
timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 600 # Set timer to 600 seconds

# Text to speech
tts:
  - platform: google_translate

#telegram notifications
telegram_bot:
  - platform: polling
    api_key: !secret telegram_token
    allowed_chat_ids:
      - !secret brenton_chatid
      - !secret amy_chatid

notify:
  - name: telegram_brenton
    platform: telegram
    chat_id: !secret brenton_chatid
  - name: telegram_amy
    platform: telegram
    chat_id: !secret amy_chatid
    
webhook:

#Ziggbe2MQTT Network Map Config
#zigbee2mqtt_networkmap:
#panel_iframe:
#  networkmap:
#    title: 'Zigbee Map'
#    url: '/local/community/zigbee2mqtt_networkmap/map.html'
#    icon: 'mdi:graphql'

# Switch config for Kogan Smart Plug
switch:
  - platform: mqtt
    name: "living_lamp"
    state_topic: "stat/living_lamp/POWER"
    command_topic: "cmnd/living_lamp/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

#Google Assitant Config
google_assistant:
  project_id: berylhassio
  service_account: !include google_service_account.json
  report_state: true
  secure_devices_pin: !secret devices_pin
  exposed_domains:
    - switch
    - light
  entity_config:
    switch.sonoff_sonoff:
      name: Bin Lights
    switch.living_lamp:
      name: Living Room Lamp
    switch.gate:
      name: Front Gate
    
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml