
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
frontend:
  themes: !include themes.yaml
  extra_module_url:
    - \config\www\community\lovelace-card-mod/card-mod.js

media_extractor:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Zigbee2mqtt MQTT Broker Config
mqtt:
  broker: homeassistant # This will have to be your mqtt broker, Mosquitto addon is recommended.
  discovery: true
  username: brenton
  password: !secret mqtt_password

# Zigbee2MQTT Card
input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless
    
# Timer for Zigbee2MQTT
timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 600 # Set timer to 600 seconds

# Text to speech
tts:
  - platform: google_translate

#telegram notifications
telegram_bot:
  - platform: polling
    api_key: !secret telegram_token
    allowed_chat_ids:
      - !secret brenton_chatid
      - !secret amy_chatid

notify:
  - name: telegram_brenton
    platform: telegram
    chat_id: !secret brenton_chatid
  - name: telegram_amy
    platform: telegram
    chat_id: !secret amy_chatid
    
webhook:

# Switch config for Kogan Smart Plug
switch:
  - platform: mqtt
    name: "living_lamp"
    state_topic: "stat/living_lamp/POWER"
    command_topic: "cmnd/living_lamp/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

#Google Assitant Config
google_assistant:
  project_id: berylhassio
  service_account: !include google_service_account.json
  report_state: true
  secure_devices_pin: !secret devices_pin
  exposed_domains:
    - switch
    - light
    - lock
  entity_config:
    switch.sonoff_sonoff:
      name: Bin Lights
    switch.living_lamp:
      name: Living Room Lamp
    switch.gate:
      name: Front Gate
    cover.garage_door:
      name: Garage Door Cover Test
    
  
binary_sensor:
- platform: workday
  country: AU
  province: QLD
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun]

#Sonos Cloud
sonos_cloud:
  client_id: !secret sonos_id
  client_secret: !secret sonos_secret

#Testing Cover Script
cover:
- platform: template
  covers:
    garage_door:
      friendly_name: "Garage Door Cover Test"
      value_template: "{{ is_state('binary_sensor.garage_door_sensor', 'on') }}"
      open_cover:
        service: switch.toggle
        data:
          entity_id: switch.garage_garage
      close_cover:
        service: switch.toggle
        data:
          entity_id: switch.garage_garage
      icon_template: >-
        {% if states('binary_sensor.garage_door_sensor_contact') == "on" %}
          mdi:garage-open-variant
        {% else %}
          mdi:garage-variant
        {% endif %}  

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml