# MQTT platform entity displayed in zigbee2mqtt card
- platform: mqtt
  name: Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless

# Power Consumption for kogan smart plug that controls lamp
- platform: mqtt
  name: "living_lamp Power Consumption"
  state_topic: "tele/living_lamp/SENSOR"
  value_template: "{{ value_json.ENERGY.Power }}"
  unit_of_measurement: "Watts"

# System Monitor Status for Raspberry Pi 3+
- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /home
  - type: swap_use_percent
    arg: /home
  - type: memory_free
  - type: processor_use
  - type: memory_use
  - type: load_1m
  - type: load_5m
  - type: load_15m
  - type: last_boot

- platform: steam_online
  api_key: !secret steam_api
  accounts:
    - 76561198020324018
    - 76561197965532072
    
- platform: template
  sensors:
    steam_last_online:
      friendly_name: Paul Oberman Last Online
      value_template: "{{ state_attr('sensor.steam_76561198020324018','last_online') }}"
      device_class: timestamp
      
    steam_last_online:
      friendly_name: Paul Black Last Online
      value_template: "{{ state_attr('sensor.steam_76561197965532072','last_online') }}"
      device_class: timestamp