#Wind Direction Sensor
- platform: template
  sensors:
    wind_direction:
      friendly_name: Wind Direction
      value_template: >
        {% set direction = ['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSW','SW','WSW','W','WNW','NW','NNW','N'] %}
        {% set degree = states('sensor.gw1100c_v2_1_4_wind_direction')|float %}
        {{ direction[((degree+11.25)/22.5)|int] }}